input = "./test/pemtim"
output = "./test/pemtimout"
pemspe = "./test/pemspe"
windinputfile = "./test/windinput.csv"
windoutputfile = "./test/windoutput.csv"
mode = 1 # 0 = spray, 1 = calpuff, 2 = impact
sources = [
    # sorgente odorigena
    { id = 1, scheme = 1, species = ["OU"], height = 5, terrain = "rural", vref = 0.6},
    # erosione cumulo di polveri con base dati vento disponibile 
    # forma piramidale (xmin, xmax, ymin, ymax)
    { id = 2, scheme = 2, species = ["PTS", "PM25", "PM10"], height = 4, xmax = 5, xmin = 2, ymin = 2, ymax = 5, mass = 2.5E+10, roughness = 0.005, tfv = 0.05},  
    # forma conica (radius)
    { id = 3, scheme = 2, species = ["PTS", "PM25", "PM10"], height = 4, radius = 3, mass = 2.5E+10, roughness = 0.005, tfv = 0.05},  
    # forma "piatta" (diameter) 
    { id = 4, scheme = 2, species = ["PTS", "PM25", "PM10"], height = 4, diameter = 5, mass = 2.5E+10, roughness = 0.005, tfv = 0.05},  
    # erosione cumulo di polveri con base dati vento non disponibile (radius è il raggio equivalente)
    { id = 5, scheme = 3, species = ["PTS", "PM25", "PM10"], height = 4, radius = 3.6, movh = 4} 
]

# mass in microgrammi
# roughness in metri
# (radius, diameter, xmax, xmin, ymax, ymin, height) in metri
# movh numero movimentazioni all'ora
# tfv threshold friction velocity in metri al secondo
# vref velocità di riferimento per il fattore emissivo odorigeno in metri al secondo
# terrain = "rural" o "urban"



#####################################################################################
# Selects EPA parameters according to material:
## Threshold friction velocity (m/s)
# tfv = {'overburden':  1.02,
#       'scoria':      1.33,
#       'ground_coal': 0.55,
#       'uncrusted_coal_pile': 1.12,
#       'scraper_tracks' : 0.62,
#       'fine_coal_dust' : 0.54,
#       'custom_pile' : 0.62
#       }
## Roughness height (cm)
# rh  = {'overburden':  0.3,
#       'scoria':      0.3,
#       'ground_coal': 0.01,
#       'uncrusted_coal_pile': 0.3,
#       'scraper_tracks' : 0.06,
#       'fine_coal_dust' : 0.2,
#       'custom_pile' : 0.15
#       }
