input = "./test/pemtim"
output = "./test/pemtimout"
# pemspe serve soltanto nella modalità spray (mode = 0)
pemspe = "./test/pemspe" 
windinputfile = "./test/windinput.csv"
windoutputfile = "./test/windoutput.csv"
mode = 0 # 0 = spray, 1 = calpuff, 2 = impact, 3 = aermod
sources = [
    # sorgente odorigena
    { id = 1, scheme = 1, species = ["OU"], height = 5, terrain = "rural", vref = 0.6},
    # erosione cumulo di polveri con base dati vento disponibile 
    # forma piramidale (xmin, xmax, ymin, ymax)
    { id = 2, scheme = 2, species = ["PTS", "PM25", "PM10"], height = 4, major = 5, minor = 3, angle = 10, roughness = 0.3, tfv = 0.05},  
    # forma conica (radius)
    { id = 3, scheme = 2, species = ["PTS", "PM25", "PM10"], height = 4, radius = 3, roughness = 0.15, tfv = 0.05},  
    # erosione cumulo di polveri con base dati vento non disponibile (radius è il raggio equivalente)
    { id = 5, scheme = 3, species = ["PTS", "PM25", "PM10"], height = 4, radius = 3.6, movh = 4} 
]

# roughness in centimetri
# (radius, diameter, major, minor, height) in metri
# (angle) in gradi (-90,+90)
# movh numero movimentazioni all'ora
# tfv threshold friction velocity in metri al secondo
# vref velocità di riferimento per il fattore emissivo odorigeno in metri al secondo
# terrain = "rural" o "urban"



#####################################################################################
# Selects EPA parameters according to material:
## Threshold friction velocity (m/s)
# tfv = {'overburden':  1.02,
#       'scoria':      1.33,
#       'ground_coal': 0.55,
#       'uncrusted_coal_pile': 1.12,
#       'scraper_tracks' : 0.62,
#       'fine_coal_dust' : 0.54,
#       'custom_pile' : 0.62
#       }
## Roughness height (cm)
# rh  = {'overburden':  0.3,
#       'scoria':      0.3,
#       'ground_coal': 0.01,
#       'uncrusted_coal_pile': 0.3,
#       'scraper_tracks' : 0.06,
#       'fine_coal_dust' : 0.2,
#       'custom_pile' : 0.15
#       }
