input = "./test/pemtim"
output = "./test/pemtimout"
pemspe = "./test/pemspe"
windinputfile = "./test/windinput.csv"
windoutputfile = "./test/windoutput.csv"
sources = [1, 2]
scheme = [1, 1]
# 1 = odore, 2 = polveri da cumuli bassi, 3 = polvere da cumuli alti, etc.
height = [5, 5]
species = ["NOX"]
terrain = "rural"
movh = [5, 4] # movimentazioni all'ora
