#
# SPDX-FileCopyrightText: 2023 Simularia s.r.l. <info@simualaria.it>
#
# SPDX-License-Identifier: AGPL-3.0-or-later
#

input = "./test/pemtim"
output = "./test/pemtimout"
# pemspe only needed in spray mode (mode = 0)
pemspe = "./test/pemspe" 
# mettype = 'postbin'
windInputFile = "./test/windinput.csv"
windOutpuFfile = "./test/windoutput.csv"
mode = 0 # 0 = spray, 1 = calpuff, 2 = impact, 3 = aermod
sources = [
    # odour source
    { id = 1, scheme = 1, species = ["OU"], height = 5, terrain = "rural", vref = 0.6},
    # wind erosion with available wind data
    # pyramid shape
    { id = 2, scheme = 2, species = ["PTS", "PM25", "PM10"], height = 4, major = 5, minor = 3, angle = 10, roughness = 0.3, tfv = 0.05},  
    # conical shape
    { id = 3, scheme = 2, species = ["PTS", "PM25", "PM10"], height = 4, radius = 3, roughness = 0.15, tfv = 0.05},  
    # wind erosion with no available wind data
    { id = 5, scheme = 3, species = ["PTS", "PM25", "PM10"], height = 4, radius = 3.6, movh = 4},

    # examples of compact description of multiple sources with same characteristics (it works with each possible scheme)
    { id = [1, 'source1', 'source 2'], scheme = 3, species = ["PTS", "PM25", "PM10"], height = 4, radius = 3.6, movh = 4},
    { id = [1, 22, 333], scheme = 3, species = ["PTS", "PM25", "PM10"], height = 4, radius = 3.6, movh = 4}
]

# roughness in cm
# (radius, diameter, major, minor, height) in meters
# (angle) in gradi (-90,+90)
# movh hourly movement number
# tfv threshold friction velocity in m/s
# vref reference velocity for odour emission factor (m/s)
# terrain = "rural" o "urban"



#####################################################################################
# Selects EPA parameters according to material:
## Threshold friction velocity (m/s)
# tfv = {'overburden':  1.02,
#       'scoria':      1.33,
#       'ground_coal': 0.55,
#       'uncrusted_coal_pile': 1.12,
#       'scraper_tracks' : 0.62,
#       'fine_coal_dust' : 0.54,
#       'custom_pile' : 0.62
#       }
## Roughness height (cm)
# rh  = {'overburden':  0.3,
#       'scoria':      0.3,
#       'ground_coal': 0.01,
#       'uncrusted_coal_pile': 0.3,
#       'scraper_tracks' : 0.06,
#       'fine_coal_dust' : 0.2,
#       'custom_pile' : 0.15
#       }
